on: [push, pull_request, workflow_dispatch]

name: Build

jobs:

  anna_nice_nano:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.5
    name: Anna nice!nano
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (Anna Left)
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=anna_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Anna DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/nice_nano_v2.dts.pre.tmp
      - name: Anna Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 anna_left_nice_nano_v2.uf2
      - name: Archive (Anna Left)
        uses: actions/upload-artifact@v2
        with:
          name: anna_nice_nano_v2
          path: anna_left_nice_nano_v2.uf2
      - name: West Build (Anna Right)
        run: west build --pristine -s zmk/app -b nice_nano_v2 -- -DSHIELD=anna_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Anna Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 anna_right_nice_nano_v2.uf2
      - name: Archive (Anna Right)
        uses: actions/upload-artifact@v2
        with:
          name: anna_nice_nano_v2
          path: anna_right_nice_nano_v2.uf2
